export type RootStackParamList = {
  //Welcome Screen
  Welcome: undefined;
  //Login & SignUp Screen
  SignUp: undefined;
  Login: undefined;
  //Main Tabs
  Profile: undefined;
  MainTabs: undefined;
  //Journaling Screens
  Journaling: undefined;
  JournalEntry: undefined;
  BodyFeelingScreen: undefined;
  ReflectionScreen: undefined;
  TherapeuticQuestionsScreen: undefined;
  //Islamic
  Islamic: undefined;
  //ChatBot
  Chatbot: undefined;
  //
  HealthScreen: undefined;
  //Exercises
  Exercises: undefined;
  //Anger
  Anger: { taskCompleted?: boolean; taskScreen?: string };
  AngerTask1: undefined;
  AngerTask2: undefined;
  AngerTask3: undefined;
  AngerTask4: undefined;
  AngerTask5: undefined;
  AngerTask6: undefined;
  AngerTask7: undefined;
  AngerTask8: undefined;
  AngerTask9: undefined;
  AngerTask10: undefined;
  AngerTask11: undefined;
  AngerTask12: undefined;
  AngerTask13: undefined;
  AngerTask14: undefined;
  AngerTask15: undefined;
  //Anxiety
  Anxiety: { taskCompleted?: boolean; taskScreen?: string };
  AnxietyTask1: undefined;
  AnxietyTask2: undefined;
  AnxietyTask3: undefined;
  AnxietyTask4: undefined;
  AnxietyTask5: undefined;
  AnxietyTask6: undefined;
  AnxietyTask7: undefined;
  AnxietyTask8: undefined;
  AnxietyTask9: undefined;
  AnxietyTask10: undefined;
  AnxietyTask11: undefined;
  AnxietyTask12: undefined;
  //Breathing
  Breathing: { taskCompleted?: boolean; taskScreen?: string };
  BreathingTask1: undefined;
  BreathingTask2: undefined;
  BreathingTask3: undefined;
  BreathingTask4: undefined;
  BreathingTask5: undefined;
  BreathingTask6: undefined;
  BreathingTask7: undefined;
  BreathingTask8: undefined;
  BreathingTask9: undefined;
  BreathingTask10: undefined;
  BreathingTask11: undefined;
  BreathingTask12: undefined;
  //Depression
  Depression: { taskCompleted?: boolean; taskScreen?: string };
  DepressionTask1: undefined;
  DepressionTask2: undefined;
  DepressionTask3: undefined;
  DepressionTask4: undefined;
  DepressionTask5: undefined;
  DepressionTask6: undefined;
  DepressionTask7: undefined;
  DepressionTask8: undefined;
  DepressionTask9: undefined;
  DepressionTask10: undefined;
  DepressionTask11: undefined;
  DepressionTask12: undefined;
  DepressionTask13: undefined;
  DepressionTask14: undefined;
  DepressionTask15: undefined;
  //Fatigue
  Fatigue: { taskCompleted?: boolean; taskScreen?: string };
  FatigueTask1: undefined;
  FatigueTask2: undefined;
  FatigueTask3: undefined;
  FatigueTask4: undefined;
  FatigueTask5: undefined;
  FatigueTask6: undefined;
  FatigueTask7: undefined;
  FatigueTask8: undefined;
  FatigueTask9: undefined;
  FatigueTask10: undefined;
  FatigueTask11: undefined;
  FatigueTask12: undefined;
  FatigueTask13: undefined;
  FatigueTask14: undefined;
  FatigueTask15: undefined;
  //Fear
  Fear: { taskCompleted?: boolean; taskScreen?: string };
  FearTask1: undefined;
  FearTask2: undefined;
  FearTask3: undefined;
  FearTask4: undefined;
  FearTask5: undefined;
  FearTask6: undefined;
  FearTask7: undefined;
  FearTask8: undefined;
  FearTask9: undefined;
  FearTask10: undefined;
  FearTask11: undefined;
  FearTask12: undefined;
  //Fear of Loss
  FearOfLoss: { taskCompleted?: boolean; taskScreen?: string };
  FearOfLossTask1: undefined;
  FearOfLossTask2: undefined;
  FearOfLossTask3: undefined;
  FearOfLossTask4: undefined;
  FearOfLossTask5: undefined;
  FearOfLossTask6: undefined;
  FearOfLossTask7: undefined;
  FearOfLossTask8: undefined;
  FearOfLossTask9: undefined;
  FearOfLossTask10: undefined;
  FearOfLossTask11: undefined;
  FearOfLossTask12: undefined;
  //Forgiveness
  Forgiveness: { taskCompleted?: boolean; taskScreen?: string };
  ForgivenessTask1: undefined;
  ForgivenessTask2: undefined;
  ForgivenessTask3: undefined;
  ForgivenessTask4: undefined;
  ForgivenessTask5: undefined;
  ForgivenessTask6: undefined;
  ForgivenessTask7: undefined;
  ForgivenessTask8: undefined;
  ForgivenessTask9: undefined;
  ForgivenessTask10: undefined;
  ForgivenessTask11: undefined;
  ForgivenessTask12: undefined;
  ForgivenessTask13: undefined;
  ForgivenessTask14: undefined;
  ForgivenessTask15: undefined;
  //Frustration
  Frustration: { taskCompleted?: boolean; taskScreen?: string };
  FrustrationTask1: undefined;
  FrustrationTask2: undefined;
  FrustrationTask3: undefined;
  FrustrationTask4: undefined;
  FrustrationTask5: undefined;
  FrustrationTask6: undefined;
  FrustrationTask7: undefined;
  FrustrationTask8: undefined;
  FrustrationTask9: undefined;
  FrustrationTask10: undefined;
  FrustrationTask11: undefined;
  FrustrationTask12: undefined;
  FrustrationTask13: undefined;
  FrustrationTask14: undefined;
  FrustrationTask15: undefined;
  //Happiness
  Happiness: { taskCompleted?: boolean; taskScreen?: string };
  HappinessTask1: undefined;
  HappinessTask2: undefined;
  HappinessTask3: undefined;
  HappinessTask4: undefined;
  HappinessTask5: undefined;
  HappinessTask6: undefined;
  HappinessTask7: undefined;
  HappinessTask8: undefined;
  HappinessTask9: undefined;
  HappinessTask10: undefined;
  HappinessTask11: undefined;
  HappinessTask12: undefined;
  HappinessTask13: undefined;
  HappinessTask14: undefined;
  HappinessTask15: undefined;
  //Impatience
  Impatience: { taskCompleted: boolean; taskScreen?: string };
  ImpatienceTask1: undefined;
  ImpatienceTask2: undefined;
  ImpatienceTask3: undefined;
  ImpatienceTask4: undefined;
  ImpatienceTask5: undefined;
  ImpatienceTask6: undefined;
  ImpatienceTask7: undefined;
  ImpatienceTask8: undefined;
  ImpatienceTask9: undefined;
  ImpatienceTask10: undefined;
  ImpatienceTask11: undefined;
  ImpatienceTask12: undefined;
  ImpatienceTask13: undefined;
  ImpatienceTask14: undefined;
  ImpatienceTask15: undefined;
  //Irritation
  Irritation: { taskCompleted?: boolean; taskScreen?: string };
  IrritationTask1: undefined;
  IrritationTask2: undefined;
  IrritationTask3: undefined;
  IrritationTask4: undefined;
  IrritationTask5: undefined;
  IrritationTask6: undefined;
  IrritationTask7: undefined;
  IrritationTask8: undefined;
  IrritationTask9: undefined;
  IrritationTask10: undefined;
  IrritationTask11: undefined;
  IrritationTask12: undefined;
  IrritationTask13: undefined;
  IrritationTask14: undefined;
  IrritationTask15: undefined;
  //Jealousy
  Jealousy: { taskCompleted?: boolean; taskScreen?: string };
  JealousyTask1: undefined;
  JealousyTask2: undefined;
  JealousyTask3: undefined;
  JealousyTask4: undefined;
  JealousyTask5: undefined;
  JealousyTask6: undefined;
  JealousyTask7: undefined;
  JealousyTask8: undefined;
  JealousyTask9: undefined;
  JealousyTask10: undefined;
  JealousyTask11: undefined;
  JealousyTask12: undefined;
  JealousyTask13: undefined;
  JealousyTask14: undefined;
  JealousyTask15: undefined;
  //Loneliness
  Loneliness: { taskCompleted?: boolean; taskScreen?: string };
  LonelinessTask1: undefined;
  LonelinessTask2: undefined;
  LonelinessTask3: undefined;
  LonelinessTask4: undefined;
  LonelinessTask5: undefined;
  LonelinessTask6: undefined;
  LonelinessTask7: undefined;
  LonelinessTask8: undefined;
  LonelinessTask9: undefined;
  LonelinessTask10: undefined;
  LonelinessTask11: undefined;
  LonelinessTask12: undefined;
  LonelinessTask13: undefined;
  LonelinessTask14: undefined;
  LonelinessTask15: undefined;
  //Pain
  Pain: { taskCompleted?: boolean; taskScreen?: string };
  PainTask1: undefined;
  PainTask2: undefined;
  PainTask3: undefined;
  PainTask4: undefined;
  PainTask5: undefined;
  PainTask6: undefined;
  PainTask7: undefined;
  PainTask8: undefined;
  PainTask9: undefined;
  PainTask10: undefined;
  PainTask11: undefined;
  PainTask12: undefined;
  PainTask13: undefined;
  PainTask14: undefined;
  PainTask15: undefined;
  //Resentment
  Resentment: { taskCompleted?: boolean; taskScreen?: string };
  ResentmentTask1: undefined;
  ResentmentTask2: undefined;
  ResentmentTask3: undefined;
  ResentmentTask4: undefined;
  ResentmentTask5: undefined;
  //Sadness
  Sadness: { taskCompleted?: boolean; taskScreen?: string };
  SadnessTask1: undefined;
  SadnessTask2: undefined;
  SadnessTask3: undefined;
  SadnessTask4: undefined;
  SadnessTask5: undefined;
  SadnessTask6: undefined;
  SadnessTask7: undefined;
  SadnessTask8: undefined;
  SadnessTask9: undefined;
  SadnessTask10: undefined;
  SadnessTask11: undefined;
  SadnessTask12: undefined;
  SadnessTask13: undefined;
  SadnessTask14: undefined;
  SadnessTask15: undefined;
  //Self-Confidence
  SelfConfidence: { taskCompleted?: boolean; taskScreen?: string };
  SelfConfidenceTask1: undefined;
  SelfConfidenceTask2: undefined;
  SelfConfidenceTask3: undefined;
  SelfConfidenceTask4: undefined;
  SelfConfidenceTask5: undefined;
  SelfConfidenceTask6: undefined;
  SelfConfidenceTask7: undefined;
  SelfConfidenceTask8: undefined;
  SelfConfidenceTask9: undefined;
  SelfConfidenceTask10: undefined;
  SelfConfidenceTask11: undefined;
  SelfConfidenceTask12: undefined;
  SelfConfidenceTask13: undefined;
  SelfConfidenceTask14: undefined;
  SelfConfidenceTask15: undefined;
  //Shame
  Shame: { taskCompleted?: boolean; taskScreen?: string };
  ShameTask1: undefined;
  ShameTask2: undefined;
  ShameTask3: undefined;
  ShameTask4: undefined;
  ShameTask5: undefined;
  //Shyness
  Shyness: { taskCompleted?: boolean; taskScreen?: string };
  ShynessTask1: undefined;
  ShynessTask2: undefined;
  ShynessTask3: undefined;
  ShynessTask4: undefined;
  ShynessTask5: undefined;
  ShynessTask6: undefined;
  ShynessTask7: undefined;
  ShynessTask8: undefined;
  ShynessTask9: undefined;
  ShynessTask10: undefined;
  ShynessTask11: undefined;
  ShynessTask12: undefined;
  ShynessTask13: undefined;
  ShynessTask14: undefined;
  ShynessTask15: undefined;
  //Social Anxiety
  SocialAnxiety: { taskCompleted?: boolean; taskScreen?: string };
  SocialAnxietyTask1: undefined;
  SocialAnxietyTask2: undefined;
  SocialAnxietyTask3: undefined;
  SocialAnxietyTask4: undefined;
  SocialAnxietyTask5: undefined;

  //Mood Tracking
  MoodTracking: undefined;
  //HealthScreen
  Health: undefined;
};
